build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_TOTAL_PAGES: 4

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE:1
	- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE:2
	- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE:3
	- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE:4
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 4

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - python -m pip install --upgrade pip
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
