resources:
  repositories:
    - repository: templates
      type: github
      name: bincrafters/templates
      endpoint: github

jobs:
- template: .ci/azure.yml@templates
  parameters:
    conanLoginUsername: $(CONAN_LOGIN_USERNAME)
    conanPassword: $(CONAN_PASSWORD)
    splitByBuildTypes: "true"
