jobs:
- job: Linux
  pool:
    vmImage: "ubuntu-16.04"
  timeoutInMinutes: 180
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
  - script: |
      pip install --upgrade pip
      chmod +x .ci/install.sh
      ./.ci/install.sh
      chmod +x .ci/run.sh
      ./.ci/run.sh
    env:
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
      CONAN_USE_DOCKER: 1

  # bincrafters-conventions:no-new-compiler-versions  
  # Qt doesn't work with Clang 8 right now, remove tag when it does
  
  strategy:
    matrix:
      Gcc 4.9:
        CONAN_GCC_VERSIONS: 4.9
      Gcc 5:
        CONAN_GCC_VERSIONS: 5
      Gcc 6:
        CONAN_GCC_VERSIONS: 6
      Gcc 7:
        CONAN_GCC_VERSIONS: 7
      Gcc 8:
        CONAN_GCC_VERSIONS: 8
      Gcc 9:
        CONAN_GCC_VERSIONS: 9
      Clang 3.9:
        CONAN_CLANG_VERSIONS: 3.9
      Clang 4.0:
        CONAN_CLANG_VERSIONS: 4.0
      Clang 5.0:
        CONAN_CLANG_VERSIONS: 5.0
      Clang 6.0:
        CONAN_CLANG_VERSIONS: 6.0
      Clang 7.0:
        CONAN_CLANG_VERSIONS: 7.0
