resources:
  repositories:
    - repository: templates
      type: github
      name: bincrafters/templates
      endpoint: github

extends:
  template: .ci/azure.yml@templates
  parameters:
    conanLoginUsername: $(CONAN_LOGIN_USERNAME)
    conanPassword: $(CONAN_PASSWORD)
    enableAppleClangBuilds: true
    splitByBuildTypes: "true"
    requireMoreDiskSpace: "true"
